import { images } from "../images"; import type { StandardPageContent } from "@/components/marketing/StandardPage";
export const corePages:Record<string,StandardPageContent>={
  "how-it-works":{eyebrow:"A simpler service journey",title:"From home problem to handled.",description:"Choose a service, share what matters, pick an available time and follow clear booking status.",image:images.bookingHero,sections:[{title:"Start with the job",text:"Service-specific questions help BREERO understand the request without making you repeat yourself."},{title:"Validate coverage",text:"Your exact address and live availability are checked by the platform."},{title:"Review before payment",text:"Scope, timing, amount and currency come from the authoritative booking state."},{title:"Stay informed",text:"A booking is confirmed only after verified payment processing."}]},
  "why-breero":{eyebrow:"Why BREERO",title:"Confidence built into every step.",description:"A marketplace designed around clear booking, professional standards and customer-safe status.",image:images.quality,sections:[{title:"Less chasing",text:"One guided path replaces scattered calls, quotes and uncertainty."},{title:"Clear decisions",text:"Review the important details before committing."},{title:"Professional standards",text:"Partner information and service-relevant qualifications are checked."},{title:"Support paths",text:"Know where to go when a booking needs attention."}]},
  pricing:{eyebrow:"Pricing explained",title:"Clear before you commit.",description:"BREERO shows the server-authoritative amount and currency during booking. We do not invent universal starting prices.",image:images.bookingHero,sections:[{title:"Service scope matters",text:"The service, answers, address and appointment can all affect the booking offered."},{title:"Review first",text:"Your review step shows the authoritative booking price before payment."},{title:"Additional work",text:"Work outside the agreed scope requires a separate quote and customer approval."},{title:"Refund status",text:"Eligible refund progress is shown through owner-scoped customer payment views."}]},
  trust:{eyebrow:"Trust and safety",title:"Your home deserves careful standards.",description:"BREERO combines professional checks, secure payment handling and owner-scoped customer information.",image:images.trustHero,sections:[{title:"Professional checks",text:"Partner details and relevant qualifications are reviewed for marketplace participation."},{title:"Payment safety",text:"A redirect never acts as proof of payment. Verified provider events determine status."},{title:"Privacy by design",text:"Customer, vendor and technician access is scoped to the right owner or assignment."},{title:"Clear support",text:"Sensitive issues have explicit support and operational paths."}]},
  "service-guarantee":{eyebrow:"Service standards",title:"A clear commitment to service quality.",description:"BREERO sets expectations around booking accuracy, professional conduct and practical support.",image:images.trustHero,sections:[{title:"What we promise",text:"Clear booking information and customer-safe status throughout the journey."},{title:"What professionals promise",text:"Respectful conduct, appropriate care and honest communication about the work."},{title:"When plans change",text:"Support helps document the issue and identify the correct next step."},{title:"No hidden claims",text:"Guarantee language remains limited to approved operating policy."}]},
  about:{eyebrow:"About BREERO",title:"A better way to take care of your home.",description:"BREERO is building a friendly, reliable marketplace for everyday home services.",image:images.aboutHero,sections:[{title:"Our purpose",text:"Make finding and booking trusted home help feel straightforward."},{title:"Our approach",text:"Combine clear consumer design with serious operational and security standards."},{title:"Local by design",text:"Coverage is published only where serviceability is operationally supported."},{title:"Built to earn trust",text:"We avoid invented claims, fake ratings and vague promises."}]},
  contact:{eyebrow:"Contact BREERO",title:"How can we help?",description:"Choose the right path for booking help, partnership interest or business questions.",image:images.aboutHero,sections:[{title:"Customer support",text:"For booking help, use hello@breero.com and include your booking reference—not payment credentials."},{title:"Partner interest",text:"Service businesses can learn more on the partner information page."},{title:"Business enquiries",text:"Use hello@breero.com with a short description of your request."},{title:"Urgent safety",text:"For immediate danger or emergencies, contact local emergency services first."}]},
  partners:{eyebrow:"For service professionals",title:"Build trust. Do great work.",description:"Learn how BREERO partnership is intended to work. This is information—not a portal or earnings promise.",image:images.partnerHero,sections:[{title:"How partnership works",text:"Interest, business checks, service qualifications and operating standards come before marketplace activation."},{title:"What customers expect",text:"Reliable communication, respectful service and clear documentation."},{title:"What BREERO supports",text:"Structured offers, assignments and service status through approved operational tools."},{title:"Register interest",text:"Email partners@breero.com. A dedicated partner application will be linked only when it is real and accepted."}]},
  locations:{eyebrow:"Service areas",title:"Coverage is checked address by address.",description:"BREERO does not publish city coverage until operations formally supports it.",image:images.homeHero,sections:[{title:"Why exact addresses matter",text:"Service areas can depend on boundaries, service type and operational capacity."},{title:"How to check",text:"Use the canonical booking flow to validate your address securely."},{title:"No browser guessing",text:"The frontend never chooses the legal entity or claims serviceability itself."},{title:"Growing carefully",text:"New location pages will appear only after operational approval."}]},
};
