"use client";

import { useState } from "react";
import { Button, Checkbox, FormField, Input } from "@breero/ui";
import { customerApi } from "@/lib/customer/api";

type Mode="login"|"register"|"forgot"|"reset"|"verify";
export function AuthForm({mode}:{mode:Mode}){const [state,setState]=useState<"idle"|"loading"|"success"|"error">("idle");async function submit(data:FormData){setState("loading");try{if(mode==="login"){const session=await customerApi.auth.login({email:String(data.get("email")),password:String(data.get("password"))});localStorage.setItem("breero_access_token",session.access_token)}else if(mode==="register"){const session=await customerApi.auth.register({full_name:`${data.get("first_name")} ${data.get("last_name")}`,email:String(data.get("email")),password:String(data.get("password"))});localStorage.setItem("breero_access_token",session.access_token)}else await new Promise((resolve)=>setTimeout(resolve,600));setState("success")}catch{setState("error")}}
  if(state==="success")return <div className="approval-success" role="status"><span>✓</span><h2>{mode==="forgot"?"Check your inbox":mode==="verify"?"Email verified":mode==="reset"?"Password updated":mode==="register"?"Your account is ready":"Welcome back"}</h2><p>{mode==="forgot"?"If an account exists for that address, we’ve sent reset instructions.":mode==="verify"?"Your email is confirmed. You can now use your BREERO account.":mode==="reset"?"Sign in using your new password.":"Taking you to your account…"}</p><a href={mode==="login"||mode==="register"?"/account":"/account/login"}>{mode==="login"||mode==="register"?"Continue to account":"Go to sign in"} →</a></div>;
  return <form action={submit}>{mode==="register"&&<div className="form-grid"><FormField label="First name" htmlFor="first_name" required><Input id="first_name" name="first_name" autoComplete="given-name" required/></FormField><FormField label="Last name" htmlFor="last_name" required><Input id="last_name" name="last_name" autoComplete="family-name" required/></FormField></div>}{mode!=="reset"&&mode!=="verify"&&<FormField label="Email address" htmlFor="email" required><Input id="email" name="email" type="email" autoComplete="email" required/></FormField>}{["login","register","reset"].includes(mode)&&<FormField label={mode==="reset"?"New password":"Password"} htmlFor="password" hint={mode!=="login"?"Use at least 8 characters, including a number.":undefined} required><Input id="password" name="password" type="password" minLength={8} autoComplete={mode==="login"?"current-password":"new-password"} required/></FormField>}{mode==="reset"&&<FormField label="Confirm new password" htmlFor="confirm_password" required><Input id="confirm_password" name="confirm_password" type="password" minLength={8} autoComplete="new-password" required/></FormField>}{mode==="login"&&<div className="auth-options"><Checkbox label="Keep me signed in"/><a href="/account/forgot-password">Forgot password?</a></div>}{mode==="register"&&<Checkbox label="I agree to the Terms and Privacy Policy" required/>}{mode==="verify"&&<p className="auth-message">Verification link recognised for maya.thompson@example.com.</p>}{state==="error"&&<p className="auth-message auth-error" role="alert">{mode==="login"?"Those details don’t match. Check them and try again.":"We couldn’t complete that request. Please try again."}</p>}<Button type="submit" fullWidth size="lg" loading={state==="loading"}>{mode==="login"?"Sign in":mode==="register"?"Create account":mode==="forgot"?"Send reset link":mode==="reset"?"Update password":"Verify email"}</Button></form>}
