import { ArrowRightIcon, Avatar, Badge, Button, CalendarIcon, Card, CheckIcon, ClockIcon, HomeIcon, Price, ShieldIcon, StarIcon } from "@breero/ui";
import { AccountPageHeader } from "@/components/account/page-header";
import { bookings, formatDate, payments, quotes } from "@/lib/customer/data";

export const metadata = { title: "My account" };

export default function AccountDashboard() {
  const upcoming = bookings[0]; const pendingQuote = quotes.find((quote) => quote.status === "PENDING");
  const paid = payments.filter((payment) => payment.status === "CAPTURED").reduce((sum, payment) => sum + payment.captured_amount_minor, 0);
  return <><AccountPageHeader eyebrow="Welcome back" title="Good afternoon, Maya" description="Here’s what’s happening with your home." action={<Button size="sm">Book a service</Button>} /><div className="account-grid">
    <Card className="account-col-7 upcoming-card"><div className="account-card-title"><h2>Next booking</h2><a href={`/account/bookings/${upcoming.id}`}>View details <ArrowRightIcon size={15} /></a></div><div className="upcoming-card__date"><span><small>{formatDate(upcoming.window_start,{month:"short"}).toUpperCase()}</small><strong>{formatDate(upcoming.window_start,{day:"numeric"})}</strong></span><div><h3>{upcoming.service}</h3><p>09:00–11:00 · {upcoming.address}</p></div></div><div className="upcoming-card__professional"><Avatar name={upcoming.professional?.name} /><div><small>Your professional</small><strong>{upcoming.professional?.name}</strong></div><Badge variant="success"><StarIcon size={12} />{upcoming.professional?.rating}</Badge></div></Card>
    <Card className="account-col-5 quote-callout"><div><Badge variant="warning">Action needed</Badge><span>Expires 14 Aug</span></div><h2>Your plumbing quote is ready</h2><p>Review the proposed repair before your booking can be confirmed.</p><div className="quote-callout__bottom"><Price amount={(pendingQuote?.total_amount_minor ?? 0)/100} /><Button size="sm" trailingIcon={<ArrowRightIcon size={15} />}>Review quote</Button></div></Card>
    <Card className="account-col-4 metric-card"><span><CalendarIcon /></span><strong>{bookings.filter((booking)=>booking.status==="COMPLETED").length}</strong><p>Completed services</p></Card><Card className="account-col-4 metric-card"><span><ShieldIcon /></span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(paid/100)}</strong><p>Paid securely this year</p></Card><Card className="account-col-4 metric-card"><span><StarIcon /></span><strong>4.9</strong><p>Your average professional rating</p></Card>
    <Card className="account-col-7"><div className="account-card-title"><h2>Recent activity</h2><a href="/account/bookings">All bookings <ArrowRightIcon size={15}/></a></div><ul className="activity-list"><li><span><CheckIcon size={16}/></span><div><strong>Booking confirmed</strong><small>Home cleaning · {upcoming.reference}</small></div><time>Today</time></li><li><span><ClockIcon size={16}/></span><div><strong>Quote received</strong><small>Kitchen tap repair · BR-240802</small></div><time>Today</time></li><li><span><ShieldIcon size={16}/></span><div><strong>Payment complete</strong><small>Electrical safety check · £110.00</small></div><time>28 Jul</time></li></ul></Card>
    <Card className="account-col-5"><div className="account-card-title"><h2>Quick actions</h2></div><div className="quick-actions"><a href="/services"><CalendarIcon/>Book again</a><a href="/account/addresses"><HomeIcon/>Addresses</a><a href="/help"><ShieldIcon/>Get support</a></div></Card>
  </div></>;
}
